server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/MazFreeLancer/BCP1-Config-Data
  application:
    name: Config-Server